language: node_js
node_js:
  - "0.10"
install:
  - "bin/installDeps.sh"
  - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"
  - "web: node node_modules/ep_etherpad-lite/node/server.js"
  - "cp src/package.json ./"
  - "npm install"
  - "zip -r etherpad-lite-cf-offline ./*"
